package com.leesin.json.compare.json;

import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

/**
 * @description: 比较json数据是否相同
 * [map返回的是没有顺序的，所以json中也没有顺序，需要转化为对象比较]
 *
 * @author: dongxueyuan
 * @date: Created in 2020/11/19 4:39 下午
 *
 *
 * 来自：https://segmentfault.com/a/1190000009523237
 * 注意：不能是list，如果是response，就比较response，不要比较result
 */
public class Compare {
    public static void main(String[] args) {
        String json1 = "{\n" +
                "\t\"code\": \"8000\",\n" +
                "\t\"msg\": \"SUCCESS\",\n" +
                "\t\"success\": true,\n" +
                "\t\"result\": [{\n" +
                "\t\t\"parentId\": \"e628ac2c960e1f92637e31eee59f3877\",\n" +
                "\t\t\"catName\": \"游戏\",\n" +
                "\t\t\"catIcon\": \"https://tphoto.bxapp.cn/upload/assets/game_new.png\",\n" +
                "\t\t\"orderNo\": null,\n" +
                "\t\t\"subCatList\": [{\n" +
                "\t\t\t\"catId\": \"1004be1cff184887a9add81580d31bf3\",\n" +
                "\t\t\t\"catName\": \"逃离塔科夫\",\n" +
                "\t\t\t\"catIcon\": \"https://tphoto.bxapp.cn/c4fff95d177e4999abdfbddceceed263.png\",\n" +
                "\t\t\t\"appLevel\": 5,\n" +
                "\t\t\t\"isOnline\": 1,\n" +
                "\t\t\t\"poiKeyword\": \"\",\n" +
                "\t\t\t\"poiTypeCode\": \"\",\n" +
                "\t\t\t\"unit\": \"小时\",\n" +
                "\t\t\t\"maxOrdersDay\": 3,\n" +
                "\t\t\t\"isTimelyAppointment\": 0,\n" +
                "\t\t\t\"scheme\": null,\n" +
                "\t\t\t\"levelOptions\": []\n" +
                "\t\t}]\n" +
                "\t}, {\n" +
                "\t\t\"parentId\": \"7e522ed7a2aa7f8c1d423bdd42461192\",\n" +
                "\t\t\"catName\": \"线下娱乐\",\n" +
                "\t\t\"catIcon\": \"https://tphoto.bxapp.cn/upload/assets/xxyl_online.png\",\n" +
                "\t\t\"orderNo\": null,\n" +
                "\t\t\"subCatList\": [{\n" +
                "\t\t\t\"catId\": \"067aeaa0542ebd54881f1de5ac66ae0b\",\n" +
                "\t\t\t\"catName\": \"桌球\",\n" +
                "\t\t\t\"catIcon\": \"https://tphoto.bxapp.cn/upload/assets/snooker.png\",\n" +
                "\t\t\t\"appLevel\": 5,\n" +
                "\t\t\t\"isOnline\": 1,\n" +
                "\t\t\t\"poiKeyword\": \"桌球吧|台球厅|棋牌室\",\n" +
                "\t\t\t\"poiTypeCode\": \"080113|080000\",\n" +
                "\t\t\t\"unit\": \"小时\",\n" +
                "\t\t\t\"maxOrdersDay\": 3,\n" +
                "\t\t\t\"isTimelyAppointment\": 1,\n" +
                "\t\t\t\"scheme\": null,\n" +
                "\t\t\t\"levelOptions\": []\n" +
                "\t\t}, {\n" +
                "\t\t\t\"catId\": \"262a0f1bb9fbb307ff8a9535c24b4094\",\n" +
                "\t\t\t\"catName\": \"陪打牌\",\n" +
                "\t\t\t\"catIcon\": \"https://tphoto.bxapp.cn/upload/assets/playcards.png\",\n" +
                "\t\t\t\"appLevel\": 5,\n" +
                "\t\t\t\"isOnline\": 1,\n" +
                "\t\t\t\"poiKeyword\": \"棋牌室|桌游\",\n" +
                "\t\t\t\"poiTypeCode\": \"080306\",\n" +
                "\t\t\t\"unit\": \"小时\",\n" +
                "\t\t\t\"maxOrdersDay\": 3,\n" +
                "\t\t\t\"isTimelyAppointment\": 1,\n" +
                "\t\t\t\"scheme\": null,\n" +
                "\t\t\t\"levelOptions\": []\n" +
                "\t\t}]\n" +
                "\t}, {\n" +
                "\t\t\"parentId\": \"351c8b215e73492db82598b8022eea8f\",\n" +
                "\t\t\"catName\": \"测试一级2\",\n" +
                "\t\t\"catIcon\": \"https://tphoto.bxapp.cn/d98a1ec2-b628-47ee-97a2-ec949f6c6118.png\",\n" +
                "\t\t\"orderNo\": null,\n" +
                "\t\t\"subCatList\": [{\n" +
                "\t\t\t\"catId\": \"be6c6597390543d290e670bf271bdcc0\",\n" +
                "\t\t\t\"catName\": \"测试二级1\",\n" +
                "\t\t\t\"catIcon\": \"https://tphoto.bxapp.cn/adee9d48-a4ee-462a-b8fd-9d5092ce6d45.png\",\n" +
                "\t\t\t\"appLevel\": 5,\n" +
                "\t\t\t\"isOnline\": 1,\n" +
                "\t\t\t\"poiKeyword\": \"\",\n" +
                "\t\t\t\"poiTypeCode\": \"\",\n" +
                "\t\t\t\"unit\": \"小时\",\n" +
                "\t\t\t\"maxOrdersDay\": 3,\n" +
                "\t\t\t\"isTimelyAppointment\": 1,\n" +
                "\t\t\t\"scheme\": null,\n" +
                "\t\t\t\"levelOptions\": []\n" +
                "\t\t}]\n" +
                "\t}, {\n" +
                "\t\t\"parentId\": \"bde74c2216c72f7b86fe84cb7eb45774\",\n" +
                "\t\t\"catName\": \"线上游戏\",\n" +
                "\t\t\"catIcon\": \"https://tphoto.bxapp.cn/upload/assets/game_online.png\",\n" +
                "\t\t\"orderNo\": null,\n" +
                "\t\t\"subCatList\": [{\n" +
                "\t\t\t\"catId\": \"08f02ad405f2433f81774780c5f45a73\",\n" +
                "\t\t\t\"catName\": \"王牌战士\",\n" +
                "\t\t\t\"catIcon\": \"https://tphoto.bxapp.cn/7326368627f44362b96df70e7d19b97e.png\",\n" +
                "\t\t\t\"appLevel\": 3,\n" +
                "\t\t\t\"isOnline\": 1,\n" +
                "\t\t\t\"poiKeyword\": \"\",\n" +
                "\t\t\t\"poiTypeCode\": \"\",\n" +
                "\t\t\t\"unit\": \"小时\",\n" +
                "\t\t\t\"maxOrdersDay\": 3,\n" +
                "\t\t\t\"isTimelyAppointment\": 1,\n" +
                "\t\t\t\"scheme\": null,\n" +
                "\t\t\t\"levelOptions\": []\n" +
                "\t\t}, {\n" +
                "\t\t\t\"catId\": \"b2f36bbf94624eda70367bb5146e8bcf\",\n" +
                "\t\t\t\"catName\": \"LOL\",\n" +
                "\t\t\t\"catIcon\": \"https://tphoto.bxapp.cn/a9ad904786884e27909d13182683a7ce.png\",\n" +
                "\t\t\t\"appLevel\": 3,\n" +
                "\t\t\t\"isOnline\": 1,\n" +
                "\t\t\t\"poiKeyword\": \"\",\n" +
                "\t\t\t\"poiTypeCode\": \"\",\n" +
                "\t\t\t\"unit\": \"局\",\n" +
                "\t\t\t\"maxOrdersDay\": 3,\n" +
                "\t\t\t\"isTimelyAppointment\": 1,\n" +
                "\t\t\t\"scheme\": null,\n" +
                "\t\t\t\"levelOptions\": [{\n" +
                "\t\t\t\t\"key\": \"all\",\n" +
                "\t\t\t\t\"value\": \"全部\"\n" +
                "\t\t\t}, {\n" +
                "\t\t\t\t\"key\": \"bojin\",\n" +
                "\t\t\t\t\"value\": \"铂金以上\"\n" +
                "\t\t\t}, {\n" +
                "\t\t\t\t\"key\": \"zuanshi\",\n" +
                "\t\t\t\t\"value\": \"钻石以上\"\n" +
                "\t\t\t}, {\n" +
                "\t\t\t\t\"key\": \"dashi\",\n" +
                "\t\t\t\t\"value\": \"大师以上\"\n" +
                "\t\t\t}, {\n" +
                "\t\t\t\t\"key\": \"zongshi\",\n" +
                "\t\t\t\t\"value\": \"宗师以上\"\n" +
                "\t\t\t}, {\n" +
                "\t\t\t\t\"key\": \"wangzhe\",\n" +
                "\t\t\t\t\"value\": \"最强王者\"\n" +
                "\t\t\t}]\n" +
                "\t\t}, {\n" +
                "\t\t\t\"catId\": \"8efb76c4477637c4c70352b8ce2be686\",\n" +
                "\t\t\t\"catName\": \"王者荣耀\",\n" +
                "\t\t\t\"catIcon\": \"https://tphoto.bxapp.cn/1c877c5870984f5e927186f0291076c2.png\",\n" +
                "\t\t\t\"appLevel\": 5,\n" +
                "\t\t\t\"isOnline\": 1,\n" +
                "\t\t\t\"poiKeyword\": \"网咖|电竞馆\",\n" +
                "\t\t\t\"poiTypeCode\": \"080308\",\n" +
                "\t\t\t\"unit\": \"局\",\n" +
                "\t\t\t\"maxOrdersDay\": 3,\n" +
                "\t\t\t\"isTimelyAppointment\": 1,\n" +
                "\t\t\t\"scheme\": null,\n" +
                "\t\t\t\"levelOptions\": [{\n" +
                "\t\t\t\t\"key\": \"ALL\",\n" +
                "\t\t\t\t\"value\": \"全部\"\n" +
                "\t\t\t}, {\n" +
                "\t\t\t\t\"key\": \"two\",\n" +
                "\t\t\t\t\"value\": \"钻石及以下\"\n" +
                "\t\t\t}, {\n" +
                "\t\t\t\t\"key\": \"three\",\n" +
                "\t\t\t\t\"value\": \"至尊星耀\"\n" +
                "\t\t\t}, {\n" +
                "\t\t\t\t\"key\": \"four\",\n" +
                "\t\t\t\t\"value\": \"最强王者\"\n" +
                "\t\t\t}, {\n" +
                "\t\t\t\t\"key\": \"five\",\n" +
                "\t\t\t\t\"value\": \"荣耀王者\"\n" +
                "\t\t\t}]\n" +
                "\t\t}, {\n" +
                "\t\t\t\"catId\": \"8894347a61d646eb90411fd9906441df\",\n" +
                "\t\t\t\"catName\": \"测试头像\",\n" +
                "\t\t\t\"catIcon\": \"https://tphoto.bxapp.cn/1288b5aab79a49c29027d1a7986fc5c1.png\",\n" +
                "\t\t\t\"appLevel\": 3,\n" +
                "\t\t\t\"isOnline\": 1,\n" +
                "\t\t\t\"poiKeyword\": \"\",\n" +
                "\t\t\t\"poiTypeCode\": \"\",\n" +
                "\t\t\t\"unit\": \"局\",\n" +
                "\t\t\t\"maxOrdersDay\": 3,\n" +
                "\t\t\t\"isTimelyAppointment\": 1,\n" +
                "\t\t\t\"scheme\": null,\n" +
                "\t\t\t\"levelOptions\": []\n" +
                "\t\t}, {\n" +
                "\t\t\t\"catId\": \"12ba6d6099d042f8be7b617b4f37495c\",\n" +
                "\t\t\t\"catName\": \"使命召唤战区\",\n" +
                "\t\t\t\"catIcon\": \"https://tphoto.bxapp.cn/3e98ec1eb8f2402cb77d43dbf7e73af1.png\",\n" +
                "\t\t\t\"appLevel\": 5,\n" +
                "\t\t\t\"isOnline\": 1,\n" +
                "\t\t\t\"poiKeyword\": \"\",\n" +
                "\t\t\t\"poiTypeCode\": \"\",\n" +
                "\t\t\t\"unit\": \"小时\",\n" +
                "\t\t\t\"maxOrdersDay\": 3,\n" +
                "\t\t\t\"isTimelyAppointment\": 0,\n" +
                "\t\t\t\"scheme\": null,\n" +
                "\t\t\t\"levelOptions\": []\n" +
                "\t\t}, {\n" +
                "\t\t\t\"catId\": \"471028758308978688\",\n" +
                "\t\t\t\"catName\": \"和平精英\",\n" +
                "\t\t\t\"catIcon\": \"https://tphoto.bxapp.cn/7b9f2e495562475f8367890dbf9bd579.png\",\n" +
                "\t\t\t\"appLevel\": 5,\n" +
                "\t\t\t\"isOnline\": 1,\n" +
                "\t\t\t\"poiKeyword\": \"\",\n" +
                "\t\t\t\"poiTypeCode\": \"\",\n" +
                "\t\t\t\"unit\": \"小时\",\n" +
                "\t\t\t\"maxOrdersDay\": 3,\n" +
                "\t\t\t\"isTimelyAppointment\": 0,\n" +
                "\t\t\t\"scheme\": null,\n" +
                "\t\t\t\"levelOptions\": []\n" +
                "\t\t}, {\n" +
                "\t\t\t\"catId\": \"378236400593534976\",\n" +
                "\t\t\t\"catName\": \"泡泡堂\",\n" +
                "\t\t\t\"catIcon\": \"https://tphoto.bxapp.cn/upload/assets/paopaotang.png\",\n" +
                "\t\t\t\"appLevel\": 5,\n" +
                "\t\t\t\"isOnline\": 1,\n" +
                "\t\t\t\"poiKeyword\": \"\",\n" +
                "\t\t\t\"poiTypeCode\": \"\",\n" +
                "\t\t\t\"unit\": \"局\",\n" +
                "\t\t\t\"maxOrdersDay\": 3,\n" +
                "\t\t\t\"isTimelyAppointment\": 1,\n" +
                "\t\t\t\"scheme\": null,\n" +
                "\t\t\t\"levelOptions\": []\n" +
                "\t\t}]\n" +
                "\t}, {\n" +
                "\t\t\"parentId\": \"88c5660a35783b80df9a883e3cd6a510\",\n" +
                "\t\t\"catName\": \"心理咨询\",\n" +
                "\t\t\"catIcon\": \"https://tphoto.bxapp.cn/upload/assets/xlzx.png\",\n" +
                "\t\t\"orderNo\": null,\n" +
                "\t\t\"subCatList\": [{\n" +
                "\t\t\t\"catId\": \"9cdb305622c046cc981efc1bcd5c39ae\",\n" +
                "\t\t\t\"catName\": \"连麦观影\",\n" +
                "\t\t\t\"catIcon\": \"\",\n" +
                "\t\t\t\"appLevel\": 5,\n" +
                "\t\t\t\"isOnline\": 1,\n" +
                "\t\t\t\"poiKeyword\": \"\",\n" +
                "\t\t\t\"poiTypeCode\": \"\",\n" +
                "\t\t\t\"unit\": \"局\",\n" +
                "\t\t\t\"maxOrdersDay\": 3,\n" +
                "\t\t\t\"isTimelyAppointment\": 1,\n" +
                "\t\t\t\"scheme\": null,\n" +
                "\t\t\t\"levelOptions\": []\n" +
                "\t\t}]\n" +
                "\t}, {\n" +
                "\t\t\"parentId\": \"f2e8a407843c750c0c23e0674a45a090\",\n" +
                "\t\t\"catName\": \"线上娱乐\",\n" +
                "\t\t\"catIcon\": \"https://tphoto.bxapp.cn/upload/assets/xxyl_offline.png\",\n" +
                "\t\t\"orderNo\": null,\n" +
                "\t\t\"subCatList\": [{\n" +
                "\t\t\t\"catId\": \"e34f04c3cd344a2caa555cd81c4c0c1a\",\n" +
                "\t\t\t\"catName\": \"线下LOL\",\n" +
                "\t\t\t\"catIcon\": \"https://tphoto.bxapp.cn/afd4e622-4c48-4bd8-99d3-979661c0e574.png\",\n" +
                "\t\t\t\"appLevel\": 5,\n" +
                "\t\t\t\"isOnline\": 1,\n" +
                "\t\t\t\"poiKeyword\": \"\",\n" +
                "\t\t\t\"poiTypeCode\": \"\",\n" +
                "\t\t\t\"unit\": \"10分钟\",\n" +
                "\t\t\t\"maxOrdersDay\": 3,\n" +
                "\t\t\t\"isTimelyAppointment\": 1,\n" +
                "\t\t\t\"scheme\": null,\n" +
                "\t\t\t\"levelOptions\": []\n" +
                "\t\t}, {\n" +
                "\t\t\t\"catId\": \"a8cf01730df4d190979309d6ab89d767\",\n" +
                "\t\t\t\"catName\": \"线上观影\",\n" +
                "\t\t\t\"catIcon\": \"https://tphoto.bxapp.cn/upload/assets/movie_online.png\",\n" +
                "\t\t\t\"appLevel\": 5,\n" +
                "\t\t\t\"isOnline\": 1,\n" +
                "\t\t\t\"poiKeyword\": \"\",\n" +
                "\t\t\t\"poiTypeCode\": \"\",\n" +
                "\t\t\t\"unit\": \"部\",\n" +
                "\t\t\t\"maxOrdersDay\": 3,\n" +
                "\t\t\t\"isTimelyAppointment\": 1,\n" +
                "\t\t\t\"scheme\": null,\n" +
                "\t\t\t\"levelOptions\": []\n" +
                "\t\t}, {\n" +
                "\t\t\t\"catId\": \"bf78dd67d648dc541dff0dc86f8af718\",\n" +
                "\t\t\t\"catName\": \"线上歌手\",\n" +
                "\t\t\t\"catIcon\": \"https://tphoto.bxapp.cn/upload/assets/xsgs_new.png\",\n" +
                "\t\t\t\"appLevel\": 5,\n" +
                "\t\t\t\"isOnline\": 1,\n" +
                "\t\t\t\"poiKeyword\": \"\",\n" +
                "\t\t\t\"poiTypeCode\": \"\",\n" +
                "\t\t\t\"unit\": \"首\",\n" +
                "\t\t\t\"maxOrdersDay\": 3,\n" +
                "\t\t\t\"isTimelyAppointment\": 1,\n" +
                "\t\t\t\"scheme\": null,\n" +
                "\t\t\t\"levelOptions\": []\n" +
                "\t\t}, {\n" +
                "\t\t\t\"catId\": \"2965e43d3689478385d03f981a3aadc1\",\n" +
                "\t\t\t\"catName\": \"使命召唤战区\",\n" +
                "\t\t\t\"catIcon\": \"https://tphoto.bxapp.cn/fbfc8dd6de7f4b908b4291998b04a94c.png\",\n" +
                "\t\t\t\"appLevel\": 5,\n" +
                "\t\t\t\"isOnline\": 1,\n" +
                "\t\t\t\"poiKeyword\": \"\",\n" +
                "\t\t\t\"poiTypeCode\": \"\",\n" +
                "\t\t\t\"unit\": \"局\",\n" +
                "\t\t\t\"maxOrdersDay\": 3,\n" +
                "\t\t\t\"isTimelyAppointment\": 1,\n" +
                "\t\t\t\"scheme\": null,\n" +
                "\t\t\t\"levelOptions\": []\n" +
                "\t\t}, {\n" +
                "\t\t\t\"catId\": \"536943410519474176\",\n" +
                "\t\t\t\"catName\": \"过新年\",\n" +
                "\t\t\t\"catIcon\": \"\",\n" +
                "\t\t\t\"appLevel\": 5,\n" +
                "\t\t\t\"isOnline\": 1,\n" +
                "\t\t\t\"poiKeyword\": \"\",\n" +
                "\t\t\t\"poiTypeCode\": \"\",\n" +
                "\t\t\t\"unit\": \"小时\",\n" +
                "\t\t\t\"maxOrdersDay\": 3,\n" +
                "\t\t\t\"isTimelyAppointment\": 0,\n" +
                "\t\t\t\"scheme\": null,\n" +
                "\t\t\t\"levelOptions\": []\n" +
                "\t\t}, {\n" +
                "\t\t\t\"catId\": \"534430875471839232\",\n" +
                "\t\t\t\"catName\": \"陪你过新年\",\n" +
                "\t\t\t\"catIcon\": \"https://tphoto.bxapp.cn/upload/assets/playcards.png\",\n" +
                "\t\t\t\"appLevel\": 3,\n" +
                "\t\t\t\"isOnline\": 1,\n" +
                "\t\t\t\"poiKeyword\": \"xxx\",\n" +
                "\t\t\t\"poiTypeCode\": \"\",\n" +
                "\t\t\t\"unit\": \"小时\",\n" +
                "\t\t\t\"maxOrdersDay\": 3,\n" +
                "\t\t\t\"isTimelyAppointment\": 0,\n" +
                "\t\t\t\"scheme\": null,\n" +
                "\t\t\t\"levelOptions\": []\n" +
                "\t\t}, {\n" +
                "\t\t\t\"catId\": \"537313855827607552\",\n" +
                "\t\t\t\"catName\": \"陪你过新年2\",\n" +
                "\t\t\t\"catIcon\": \"https://tphoto.bxapp.cn/upload/assets/playcards.png\",\n" +
                "\t\t\t\"appLevel\": 3,\n" +
                "\t\t\t\"isOnline\": 1,\n" +
                "\t\t\t\"poiKeyword\": \"\",\n" +
                "\t\t\t\"poiTypeCode\": \"\",\n" +
                "\t\t\t\"unit\": \"小时\",\n" +
                "\t\t\t\"maxOrdersDay\": 3,\n" +
                "\t\t\t\"isTimelyAppointment\": 0,\n" +
                "\t\t\t\"scheme\": null,\n" +
                "\t\t\t\"levelOptions\": []\n" +
                "\t\t}, {\n" +
                "\t\t\t\"catId\": \"425264227242999808\",\n" +
                "\t\t\t\"catName\": \"音乐\",\n" +
                "\t\t\t\"catIcon\": \"https://tphoto.bxapp.cn/bf737b825d67407aba793fbc479c0764.png\",\n" +
                "\t\t\t\"appLevel\": 5,\n" +
                "\t\t\t\"isOnline\": 1,\n" +
                "\t\t\t\"poiKeyword\": \"\",\n" +
                "\t\t\t\"poiTypeCode\": \"\",\n" +
                "\t\t\t\"unit\": \"首\",\n" +
                "\t\t\t\"maxOrdersDay\": 3,\n" +
                "\t\t\t\"isTimelyAppointment\": 1,\n" +
                "\t\t\t\"scheme\": null,\n" +
                "\t\t\t\"levelOptions\": []\n" +
                "\t\t}]\n" +
                "\t}, {\n" +
                "\t\t\"parentId\": \"38e186b60653a09469a4324113b3d1c0\",\n" +
                "\t\t\"catName\": \"文艺生活\",\n" +
                "\t\t\"catIcon\": \"https://tphoto.bxapp.cn/upload/assets/artlife.png\",\n" +
                "\t\t\"orderNo\": null,\n" +
                "\t\t\"subCatList\": [{\n" +
                "\t\t\t\"catId\": \"930a5cadc62a46bd9fe25663a5999441\",\n" +
                "\t\t\t\"catName\": \"五子棋\",\n" +
                "\t\t\t\"catIcon\": \"https://tphoto.bxapp.cn/c78e7f5e5d3a41c4bca4db9b12f7a584.png\",\n" +
                "\t\t\t\"appLevel\": 1,\n" +
                "\t\t\t\"isOnline\": 1,\n" +
                "\t\t\t\"poiKeyword\": \"\",\n" +
                "\t\t\t\"poiTypeCode\": \"\",\n" +
                "\t\t\t\"unit\": \"1分钟\",\n" +
                "\t\t\t\"maxOrdersDay\": 3,\n" +
                "\t\t\t\"isTimelyAppointment\": 0,\n" +
                "\t\t\t\"scheme\": null,\n" +
                "\t\t\t\"levelOptions\": []\n" +
                "\t\t}, {\n" +
                "\t\t\t\"catId\": \"af104711c9104e89bdc76ff918839c07\",\n" +
                "\t\t\t\"catName\": \"连连看\",\n" +
                "\t\t\t\"catIcon\": \"https://tphoto.bxapp.cn/cefbdea3e68a4580bb9270aa2f621fce.png\",\n" +
                "\t\t\t\"appLevel\": 1,\n" +
                "\t\t\t\"isOnline\": 1,\n" +
                "\t\t\t\"poiKeyword\": \"\",\n" +
                "\t\t\t\"poiTypeCode\": \"\",\n" +
                "\t\t\t\"unit\": \"局\",\n" +
                "\t\t\t\"maxOrdersDay\": 3,\n" +
                "\t\t\t\"isTimelyAppointment\": 0,\n" +
                "\t\t\t\"scheme\": null,\n" +
                "\t\t\t\"levelOptions\": []\n" +
                "\t\t}, {\n" +
                "\t\t\t\"catId\": \"587b8da9b832b013e2aca3e171aae07c\",\n" +
                "\t\t\t\"catName\": \"声优聊天\",\n" +
                "\t\t\t\"catIcon\": \"https://tphoto.bxapp.cn/upload/assets/sy_new.png\",\n" +
                "\t\t\t\"appLevel\": 5,\n" +
                "\t\t\t\"isOnline\": 1,\n" +
                "\t\t\t\"poiKeyword\": \"青受音,青年音,青叔音,叔音\",\n" +
                "\t\t\t\"poiTypeCode\": \"\",\n" +
                "\t\t\t\"unit\": \"小时\",\n" +
                "\t\t\t\"maxOrdersDay\": 3,\n" +
                "\t\t\t\"isTimelyAppointment\": 1,\n" +
                "\t\t\t\"scheme\": null,\n" +
                "\t\t\t\"levelOptions\": [{\n" +
                "\t\t\t\t\"key\": \"all\",\n" +
                "\t\t\t\t\"value\": \"全部\"\n" +
                "\t\t\t}, {\n" +
                "\t\t\t\t\"key\": \"zhengshi\",\n" +
                "\t\t\t\t\"value\": \"青受音\"\n" +
                "\t\t\t}, {\n" +
                "\t\t\t\t\"key\": \"third\",\n" +
                "\t\t\t\t\"value\": \"青年音\"\n" +
                "\t\t\t}, {\n" +
                "\t\t\t\t\"key\": \"four\",\n" +
                "\t\t\t\t\"value\": \"青叔音  \"\n" +
                "\t\t\t}, {\n" +
                "\t\t\t\t\"key\": \"five\",\n" +
                "\t\t\t\t\"value\": \"叔音\"\n" +
                "\t\t\t}, {\n" +
                "\t\t\t\t\"key\": \"six\",\n" +
                "\t\t\t\t\"value\": \"少萝音\"\n" +
                "\t\t\t}, {\n" +
                "\t\t\t\t\"key\": \"seven\",\n" +
                "\t\t\t\t\"value\": \"少女音\"\n" +
                "\t\t\t}, {\n" +
                "\t\t\t\t\"key\": \"eight\",\n" +
                "\t\t\t\t\"value\": \"少御音\"\n" +
                "\t\t\t}, {\n" +
                "\t\t\t\t\"key\": \"nine\",\n" +
                "\t\t\t\t\"value\": \"御姐音\"\n" +
                "\t\t\t}, {\n" +
                "\t\t\t\t\"key\": \"ten\",\n" +
                "\t\t\t\t\"value\": \"妈音\"\n" +
                "\t\t\t}]\n" +
                "\t\t}, {\n" +
                "\t\t\t\"catId\": \"548a76f6cec7f5b716a6f0e2581d3846\",\n" +
                "\t\t\t\"catName\": \"叫醒\",\n" +
                "\t\t\t\"catIcon\": \"https://tphoto.bxapp.cn/7ab739502f584b8f8df3dbb6d30b4038.png\",\n" +
                "\t\t\t\"appLevel\": 5,\n" +
                "\t\t\t\"isOnline\": 1,\n" +
                "\t\t\t\"poiKeyword\": \"\",\n" +
                "\t\t\t\"poiTypeCode\": \"\",\n" +
                "\t\t\t\"unit\": \"次\",\n" +
                "\t\t\t\"maxOrdersDay\": 3,\n" +
                "\t\t\t\"isTimelyAppointment\": 0,\n" +
                "\t\t\t\"scheme\": null,\n" +
                "\t\t\t\"levelOptions\": []\n" +
                "\t\t}, {\n" +
                "\t\t\t\"catId\": \"bfd0af06fe612a5e7348b5718d1da7a2\",\n" +
                "\t\t\t\"catName\": \"声音鉴定\",\n" +
                "\t\t\t\"catIcon\": \"https://tphoto.bxapp.cn/upload/assets/syjd.png\",\n" +
                "\t\t\t\"appLevel\": 5,\n" +
                "\t\t\t\"isOnline\": 1,\n" +
                "\t\t\t\"poiKeyword\": \"\",\n" +
                "\t\t\t\"poiTypeCode\": \"\",\n" +
                "\t\t\t\"unit\": \"次\",\n" +
                "\t\t\t\"maxOrdersDay\": 3,\n" +
                "\t\t\t\"isTimelyAppointment\": 1,\n" +
                "\t\t\t\"scheme\": null,\n" +
                "\t\t\t\"levelOptions\": []\n" +
                "\t\t}]\n" +
                "\t}, {\n" +
                "\t\t\"parentId\": \"471028758308978688\",\n" +
                "\t\t\"catName\": \"和平精英\",\n" +
                "\t\t\"catIcon\": \"https://tphoto.bxapp.cn/7b9f2e495562475f8367890dbf9bd579.png\",\n" +
                "\t\t\"orderNo\": null,\n" +
                "\t\t\"subCatList\": [{\n" +
                "\t\t\t\"catId\": \"c9c53944658043d5816df62f412f8db2\",\n" +
                "\t\t\t\"catName\": \"zj_测试\",\n" +
                "\t\t\t\"catIcon\": \"\",\n" +
                "\t\t\t\"appLevel\": 5,\n" +
                "\t\t\t\"isOnline\": 1,\n" +
                "\t\t\t\"poiKeyword\": \"\",\n" +
                "\t\t\t\"poiTypeCode\": \"\",\n" +
                "\t\t\t\"unit\": \"局\",\n" +
                "\t\t\t\"maxOrdersDay\": 3,\n" +
                "\t\t\t\"isTimelyAppointment\": 1,\n" +
                "\t\t\t\"scheme\": null,\n" +
                "\t\t\t\"levelOptions\": []\n" +
                "\t\t}]\n" +
                "\t}, {\n" +
                "\t\t\"parentId\": \"326b3aaec3fde42ac5c0c202c3adf56c\",\n" +
                "\t\t\"catName\": \"个人助理\",\n" +
                "\t\t\"catIcon\": \"https://tphoto.bxapp.cn/upload/assets/personal.png\",\n" +
                "\t\t\"orderNo\": null,\n" +
                "\t\t\"subCatList\": [{\n" +
                "\t\t\t\"catId\": \"7a4466ce3869421caa3a782da212a2a0\",\n" +
                "\t\t\t\"catName\": \"sh_test_1220\",\n" +
                "\t\t\t\"catIcon\": \"https://tphoto.bxapp.cn/90b12a258b1244f1ae9d9a59d367fbc0.png\",\n" +
                "\t\t\t\"appLevel\": 5,\n" +
                "\t\t\t\"isOnline\": 1,\n" +
                "\t\t\t\"poiKeyword\": \"\",\n" +
                "\t\t\t\"poiTypeCode\": \"\",\n" +
                "\t\t\t\"unit\": \"min\",\n" +
                "\t\t\t\"maxOrdersDay\": 3,\n" +
                "\t\t\t\"isTimelyAppointment\": 0,\n" +
                "\t\t\t\"scheme\": null,\n" +
                "\t\t\t\"levelOptions\": []\n" +
                "\t\t}, {\n" +
                "\t\t\t\"catId\": \"a00f922b59934016bdeb57b995a07463\",\n" +
                "\t\t\t\"catName\": \"嘿嘿嘿\",\n" +
                "\t\t\t\"catIcon\": \"https://tphoto.bxapp.cn/b19a2a9e8c9b480cab68c2dda8a6879b.png\",\n" +
                "\t\t\t\"appLevel\": 5,\n" +
                "\t\t\t\"isOnline\": 1,\n" +
                "\t\t\t\"poiKeyword\": \"\",\n" +
                "\t\t\t\"poiTypeCode\": \"\",\n" +
                "\t\t\t\"unit\": \"天\",\n" +
                "\t\t\t\"maxOrdersDay\": 3,\n" +
                "\t\t\t\"isTimelyAppointment\": 1,\n" +
                "\t\t\t\"scheme\": null,\n" +
                "\t\t\t\"levelOptions\": []\n" +
                "\t\t}]\n" +
                "\t}, {\n" +
                "\t\t\"parentId\": \"1adaf454908362a8e22fe5eb8cf8ad35\",\n" +
                "\t\t\"catName\": \"外语\",\n" +
                "\t\t\"catIcon\": \"https://tphoto.bxapp.cn/upload/assets/language.png\",\n" +
                "\t\t\"orderNo\": null,\n" +
                "\t\t\"subCatList\": [{\n" +
                "\t\t\t\"catId\": \"41ea6521dc7440e397b42a460febea3b\",\n" +
                "\t\t\t\"catName\": \"zj\",\n" +
                "\t\t\t\"catIcon\": \"https://tphoto.bxapp.cn/15368ae3fd954b0bba9ecb2b93a15ba4.png\",\n" +
                "\t\t\t\"appLevel\": 5,\n" +
                "\t\t\t\"isOnline\": 1,\n" +
                "\t\t\t\"poiKeyword\": \"\",\n" +
                "\t\t\t\"poiTypeCode\": \"\",\n" +
                "\t\t\t\"unit\": \"天\",\n" +
                "\t\t\t\"maxOrdersDay\": 3,\n" +
                "\t\t\t\"isTimelyAppointment\": 1,\n" +
                "\t\t\t\"scheme\": null,\n" +
                "\t\t\t\"levelOptions\": []\n" +
                "\t\t}, {\n" +
                "\t\t\t\"catId\": \"efbb1d9e39fade7899637664a2668fe2\",\n" +
                "\t\t\t\"catName\": \"日语辅导\",\n" +
                "\t\t\t\"catIcon\": \"https://tphoto.bxapp.cn/upload/assets/Love_Consultant.png\",\n" +
                "\t\t\t\"appLevel\": 3,\n" +
                "\t\t\t\"isOnline\": 1,\n" +
                "\t\t\t\"poiKeyword\": \"\",\n" +
                "\t\t\t\"poiTypeCode\": \"\",\n" +
                "\t\t\t\"unit\": \"小时\",\n" +
                "\t\t\t\"maxOrdersDay\": 3,\n" +
                "\t\t\t\"isTimelyAppointment\": 1,\n" +
                "\t\t\t\"scheme\": null,\n" +
                "\t\t\t\"levelOptions\": [{\n" +
                "\t\t\t\t\"key\": \"all\",\n" +
                "\t\t\t\t\"value\": \"全部\"\n" +
                "\t\t\t}, {\n" +
                "\t\t\t\t\"key\": \"second\",\n" +
                "\t\t\t\t\"value\": \"N3\"\n" +
                "\t\t\t}, {\n" +
                "\t\t\t\t\"key\": \"third\",\n" +
                "\t\t\t\t\"value\": \"N4\"\n" +
                "\t\t\t}, {\n" +
                "\t\t\t\t\"key\": \"four\",\n" +
                "\t\t\t\t\"value\": \"N5\"\n" +
                "\t\t\t}]\n" +
                "\t\t}, {\n" +
                "\t\t\t\"catId\": \"b815854cce2c48f0975b9ec8af5aeda8\",\n" +
                "\t\t\t\"catName\": \"asdasd\",\n" +
                "\t\t\t\"catIcon\": \"\",\n" +
                "\t\t\t\"appLevel\": 5,\n" +
                "\t\t\t\"isOnline\": 1,\n" +
                "\t\t\t\"poiKeyword\": \"\",\n" +
                "\t\t\t\"poiTypeCode\": \"\",\n" +
                "\t\t\t\"unit\": \"1\",\n" +
                "\t\t\t\"maxOrdersDay\": 3,\n" +
                "\t\t\t\"isTimelyAppointment\": 0,\n" +
                "\t\t\t\"scheme\": null,\n" +
                "\t\t\t\"levelOptions\": []\n" +
                "\t\t}, {\n" +
                "\t\t\t\"catId\": \"7cc133709fb2da581dc9cf1ed4baabfa\",\n" +
                "\t\t\t\"catName\": \"英语陪练\",\n" +
                "\t\t\t\"catIcon\": \"https://tphoto.bxapp.cn/upload/assets/english.png\",\n" +
                "\t\t\t\"appLevel\": 5,\n" +
                "\t\t\t\"isOnline\": 1,\n" +
                "\t\t\t\"poiKeyword\": \"\",\n" +
                "\t\t\t\"poiTypeCode\": \"\",\n" +
                "\t\t\t\"unit\": \"小时\",\n" +
                "\t\t\t\"maxOrdersDay\": 3,\n" +
                "\t\t\t\"isTimelyAppointment\": 1,\n" +
                "\t\t\t\"scheme\": null,\n" +
                "\t\t\t\"levelOptions\": [{\n" +
                "\t\t\t\t\"key\": \"all\",\n" +
                "\t\t\t\t\"value\": \"全部\"\n" +
                "\t\t\t}, {\n" +
                "\t\t\t\t\"key\": \"second\",\n" +
                "\t\t\t\t\"value\": \"CET-4\"\n" +
                "\t\t\t}, {\n" +
                "\t\t\t\t\"key\": \"third\",\n" +
                "\t\t\t\t\"value\": \"CET-6\"\n" +
                "\t\t\t}, {\n" +
                "\t\t\t\t\"key\": \"four\",\n" +
                "\t\t\t\t\"value\": \"TEM4\"\n" +
                "\t\t\t}, {\n" +
                "\t\t\t\t\"key\": \"five\",\n" +
                "\t\t\t\t\"value\": \"TEM8\"\n" +
                "\t\t\t}]\n" +
                "\t\t}]\n" +
                "\t}],\n" +
                "\t\"tid\": null,\n" +
                "\t\"ext\": null\n" +
                "}";
        String json2 = "{\"code\":\"8000\",\"ext\":null,\"msg\":\"SUCCESS\",\"result\":[{\"catIcon\":\"https://tphoto.bxapp.cn/upload/assets/game_new.png\",\"catName\":\"游戏\",\"orderNo\":null,\"parentId\":\"e628ac2c960e1f92637e31eee59f3877\",\"subCatList\":[{\"appLevel\":5,\"catIcon\":\"https://tphoto.bxapp.cn/c4fff95d177e4999abdfbddceceed263.png\",\"catId\":\"1004be1cff184887a9add81580d31bf3\",\"catName\":\"逃离塔科夫\",\"isOnline\":1,\"isTimelyAppointment\":0,\"levelOptions\":[],\"maxOrdersDay\":3,\"poiKeyword\":\"\",\"poiTypeCode\":\"\",\"scheme\":null,\"unit\":\"小时\"}]},{\"catIcon\":\"https://tphoto.bxapp.cn/upload/assets/xxyl_online.png\",\"catName\":\"线下娱乐\",\"orderNo\":null,\"parentId\":\"7e522ed7a2aa7f8c1d423bdd42461192\",\"subCatList\":[{\"appLevel\":5,\"catIcon\":\"https://tphoto.bxapp.cn/upload/assets/snooker.png\",\"catId\":\"067aeaa0542ebd54881f1de5ac66ae0b\",\"catName\":\"桌球\",\"isOnline\":1,\"isTimelyAppointment\":1,\"levelOptions\":[],\"maxOrdersDay\":3,\"poiKeyword\":\"桌球吧|台球厅|棋牌室\",\"poiTypeCode\":\"080113|080000\",\"scheme\":null,\"unit\":\"小时\"},{\"appLevel\":5,\"catIcon\":\"https://tphoto.bxapp.cn/upload/assets/playcards.png\",\"catId\":\"262a0f1bb9fbb307ff8a9535c24b4094\",\"catName\":\"陪打牌\",\"isOnline\":1,\"isTimelyAppointment\":1,\"levelOptions\":[],\"maxOrdersDay\":3,\"poiKeyword\":\"棋牌室|桌游\",\"poiTypeCode\":\"080306\",\"scheme\":null,\"unit\":\"小时\"}]},{\"catIcon\":\"https://tphoto.bxapp.cn/d98a1ec2-b628-47ee-97a2-ec949f6c6118.png\",\"catName\":\"测试一级2\",\"orderNo\":null,\"parentId\":\"351c8b215e73492db82598b8022eea8f\",\"subCatList\":[{\"appLevel\":5,\"catIcon\":\"https://tphoto.bxapp.cn/adee9d48-a4ee-462a-b8fd-9d5092ce6d45.png\",\"catId\":\"be6c6597390543d290e670bf271bdcc0\",\"catName\":\"测试二级1\",\"isOnline\":1,\"isTimelyAppointment\":1,\"levelOptions\":[],\"maxOrdersDay\":3,\"poiKeyword\":\"\",\"poiTypeCode\":\"\",\"scheme\":null,\"unit\":\"小时\"}]},{\"catIcon\":\"https://tphoto.bxapp.cn/upload/assets/game_online.png\",\"catName\":\"线上游戏\",\"orderNo\":null,\"parentId\":\"bde74c2216c72f7b86fe84cb7eb45774\",\"subCatList\":[{\"appLevel\":3,\"catIcon\":\"https://tphoto.bxapp.cn/7326368627f44362b96df70e7d19b97e.png\",\"catId\":\"08f02ad405f2433f81774780c5f45a73\",\"catName\":\"王牌战士\",\"isOnline\":1,\"isTimelyAppointment\":1,\"levelOptions\":[],\"maxOrdersDay\":3,\"poiKeyword\":\"\",\"poiTypeCode\":\"\",\"scheme\":null,\"unit\":\"小时\"},{\"appLevel\":3,\"catIcon\":\"https://tphoto.bxapp.cn/a9ad904786884e27909d13182683a7ce.png\",\"catId\":\"b2f36bbf94624eda70367bb5146e8bcf\",\"catName\":\"LOL\",\"isOnline\":1,\"isTimelyAppointment\":1,\"levelOptions\":[{\"key\":\"all\",\"value\":\"全部\"},{\"key\":\"bojin\",\"value\":\"铂金以上\"},{\"key\":\"zuanshi\",\"value\":\"钻石以上\"},{\"key\":\"dashi\",\"value\":\"大师以上\"},{\"key\":\"zongshi\",\"value\":\"宗师以上\"},{\"key\":\"wangzhe\",\"value\":\"最强王者\"}],\"maxOrdersDay\":3,\"poiKeyword\":\"\",\"poiTypeCode\":\"\",\"scheme\":null,\"unit\":\"局\"},{\"appLevel\":5,\"catIcon\":\"https://tphoto.bxapp.cn/1c877c5870984f5e927186f0291076c2.png\",\"catId\":\"8efb76c4477637c4c70352b8ce2be686\",\"catName\":\"王者荣耀\",\"isOnline\":1,\"isTimelyAppointment\":1,\"levelOptions\":[{\"key\":\"ALL\",\"value\":\"全部\"},{\"key\":\"two\",\"value\":\"钻石及以下\"},{\"key\":\"three\",\"value\":\"至尊星耀\"},{\"key\":\"four\",\"value\":\"最强王者\"},{\"key\":\"five\",\"value\":\"荣耀王者\"}],\"maxOrdersDay\":3,\"poiKeyword\":\"网咖|电竞馆\",\"poiTypeCode\":\"080308\",\"scheme\":null,\"unit\":\"局\"},{\"appLevel\":3,\"catIcon\":\"https://tphoto.bxapp.cn/1288b5aab79a49c29027d1a7986fc5c1.png\",\"catId\":\"8894347a61d646eb90411fd9906441df\",\"catName\":\"测试头像\",\"isOnline\":1,\"isTimelyAppointment\":1,\"levelOptions\":[],\"maxOrdersDay\":3,\"poiKeyword\":\"\",\"poiTypeCode\":\"\",\"scheme\":null,\"unit\":\"局\"},{\"appLevel\":5,\"catIcon\":\"https://tphoto.bxapp.cn/3e98ec1eb8f2402cb77d43dbf7e73af1.png\",\"catId\":\"12ba6d6099d042f8be7b617b4f37495c\",\"catName\":\"使命召唤战区\",\"isOnline\":1,\"isTimelyAppointment\":0,\"levelOptions\":[],\"maxOrdersDay\":3,\"poiKeyword\":\"\",\"poiTypeCode\":\"\",\"scheme\":null,\"unit\":\"小时\"},{\"appLevel\":5,\"catIcon\":\"https://tphoto.bxapp.cn/7b9f2e495562475f8367890dbf9bd579.png\",\"catId\":\"471028758308978688\",\"catName\":\"和平精英\",\"isOnline\":1,\"isTimelyAppointment\":0,\"levelOptions\":[],\"maxOrdersDay\":3,\"poiKeyword\":\"\",\"poiTypeCode\":\"\",\"scheme\":null,\"unit\":\"小时\"},{\"appLevel\":5,\"catIcon\":\"https://tphoto.bxapp.cn/upload/assets/paopaotang.png\",\"catId\":\"378236400593534976\",\"catName\":\"泡泡堂\",\"isOnline\":1,\"isTimelyAppointment\":1,\"levelOptions\":[],\"maxOrdersDay\":3,\"poiKeyword\":\"\",\"poiTypeCode\":\"\",\"scheme\":null,\"unit\":\"局\"}]},{\"catIcon\":\"https://tphoto.bxapp.cn/upload/assets/xlzx.png\",\"catName\":\"心理咨询\",\"orderNo\":null,\"parentId\":\"88c5660a35783b80df9a883e3cd6a510\",\"subCatList\":[{\"appLevel\":5,\"catIcon\":\"\",\"catId\":\"9cdb305622c046cc981efc1bcd5c39ae\",\"catName\":\"连麦观影\",\"isOnline\":1,\"isTimelyAppointment\":1,\"levelOptions\":[],\"maxOrdersDay\":3,\"poiKeyword\":\"\",\"poiTypeCode\":\"\",\"scheme\":null,\"unit\":\"局\"}]},{\"catIcon\":\"https://tphoto.bxapp.cn/upload/assets/xxyl_offline.png\",\"catName\":\"线上娱乐\",\"orderNo\":null,\"parentId\":\"f2e8a407843c750c0c23e0674a45a090\",\"subCatList\":[{\"appLevel\":5,\"catIcon\":\"https://tphoto.bxapp.cn/afd4e622-4c48-4bd8-99d3-979661c0e574.png\",\"catId\":\"e34f04c3cd344a2caa555cd81c4c0c1a\",\"catName\":\"线下LOL\",\"isOnline\":1,\"isTimelyAppointment\":1,\"levelOptions\":[],\"maxOrdersDay\":3,\"poiKeyword\":\"\",\"poiTypeCode\":\"\",\"scheme\":null,\"unit\":\"10分钟\"},{\"appLevel\":5,\"catIcon\":\"https://tphoto.bxapp.cn/upload/assets/movie_online.png\",\"catId\":\"a8cf01730df4d190979309d6ab89d767\",\"catName\":\"线上观影\",\"isOnline\":1,\"isTimelyAppointment\":1,\"levelOptions\":[],\"maxOrdersDay\":3,\"poiKeyword\":\"\",\"poiTypeCode\":\"\",\"scheme\":null,\"unit\":\"部\"},{\"appLevel\":5,\"catIcon\":\"https://tphoto.bxapp.cn/upload/assets/xsgs_new.png\",\"catId\":\"bf78dd67d648dc541dff0dc86f8af718\",\"catName\":\"线上歌手\",\"isOnline\":1,\"isTimelyAppointment\":1,\"levelOptions\":[],\"maxOrdersDay\":3,\"poiKeyword\":\"\",\"poiTypeCode\":\"\",\"scheme\":null,\"unit\":\"首\"},{\"appLevel\":5,\"catIcon\":\"https://tphoto.bxapp.cn/fbfc8dd6de7f4b908b4291998b04a94c.png\",\"catId\":\"2965e43d3689478385d03f981a3aadc1\",\"catName\":\"使命召唤战区\",\"isOnline\":1,\"isTimelyAppointment\":1,\"levelOptions\":[],\"maxOrdersDay\":3,\"poiKeyword\":\"\",\"poiTypeCode\":\"\",\"scheme\":null,\"unit\":\"局\"},{\"appLevel\":5,\"catIcon\":\"\",\"catId\":\"536943410519474176\",\"catName\":\"过新年\",\"isOnline\":1,\"isTimelyAppointment\":0,\"levelOptions\":[],\"maxOrdersDay\":3,\"poiKeyword\":\"\",\"poiTypeCode\":\"\",\"scheme\":null,\"unit\":\"小时\"},{\"appLevel\":3,\"catIcon\":\"https://tphoto.bxapp.cn/upload/assets/playcards.png\",\"catId\":\"534430875471839232\",\"catName\":\"陪你过新年\",\"isOnline\":1,\"isTimelyAppointment\":0,\"levelOptions\":[],\"maxOrdersDay\":3,\"poiKeyword\":\"xxx\",\"poiTypeCode\":\"\",\"scheme\":null,\"unit\":\"小时\"},{\"appLevel\":3,\"catIcon\":\"https://tphoto.bxapp.cn/upload/assets/playcards.png\",\"catId\":\"537313855827607552\",\"catName\":\"陪你过新年2\",\"isOnline\":1,\"isTimelyAppointment\":0,\"levelOptions\":[],\"maxOrdersDay\":3,\"poiKeyword\":\"\",\"poiTypeCode\":\"\",\"scheme\":null,\"unit\":\"小时\"},{\"appLevel\":5,\"catIcon\":\"https://tphoto.bxapp.cn/bf737b825d67407aba793fbc479c0764.png\",\"catId\":\"425264227242999808\",\"catName\":\"音乐\",\"isOnline\":1,\"isTimelyAppointment\":1,\"levelOptions\":[],\"maxOrdersDay\":3,\"poiKeyword\":\"\",\"poiTypeCode\":\"\",\"scheme\":null,\"unit\":\"首\"}]},{\"catIcon\":\"https://tphoto.bxapp.cn/upload/assets/artlife.png\",\"catName\":\"文艺生活\",\"orderNo\":null,\"parentId\":\"38e186b60653a09469a4324113b3d1c0\",\"subCatList\":[{\"appLevel\":1,\"catIcon\":\"https://tphoto.bxapp.cn/c78e7f5e5d3a41c4bca4db9b12f7a584.png\",\"catId\":\"930a5cadc62a46bd9fe25663a5999441\",\"catName\":\"五子棋\",\"isOnline\":1,\"isTimelyAppointment\":0,\"levelOptions\":[],\"maxOrdersDay\":3,\"poiKeyword\":\"\",\"poiTypeCode\":\"\",\"scheme\":null,\"unit\":\"1分钟\"},{\"appLevel\":1,\"catIcon\":\"https://tphoto.bxapp.cn/cefbdea3e68a4580bb9270aa2f621fce.png\",\"catId\":\"af104711c9104e89bdc76ff918839c07\",\"catName\":\"连连看\",\"isOnline\":1,\"isTimelyAppointment\":0,\"levelOptions\":[],\"maxOrdersDay\":3,\"poiKeyword\":\"\",\"poiTypeCode\":\"\",\"scheme\":null,\"unit\":\"局\"},{\"appLevel\":5,\"catIcon\":\"https://tphoto.bxapp.cn/upload/assets/sy_new.png\",\"catId\":\"587b8da9b832b013e2aca3e171aae07c\",\"catName\":\"声优聊天\",\"isOnline\":1,\"isTimelyAppointment\":1,\"levelOptions\":[{\"key\":\"all\",\"value\":\"全部\"},{\"key\":\"zhengshi\",\"value\":\"青受音\"},{\"key\":\"third\",\"value\":\"青年音\"},{\"key\":\"four\",\"value\":\"青叔音  \"},{\"key\":\"five\",\"value\":\"叔音\"},{\"key\":\"six\",\"value\":\"少萝音\"},{\"key\":\"seven\",\"value\":\"少女音\"},{\"key\":\"eight\",\"value\":\"少御音\"},{\"key\":\"nine\",\"value\":\"御姐音\"},{\"key\":\"ten\",\"value\":\"妈音\"}],\"maxOrdersDay\":3,\"poiKeyword\":\"青受音,青年音,青叔音,叔音\",\"poiTypeCode\":\"\",\"scheme\":null,\"unit\":\"小时\"},{\"appLevel\":5,\"catIcon\":\"https://tphoto.bxapp.cn/7ab739502f584b8f8df3dbb6d30b4038.png\",\"catId\":\"548a76f6cec7f5b716a6f0e2581d3846\",\"catName\":\"叫醒\",\"isOnline\":1,\"isTimelyAppointment\":0,\"levelOptions\":[],\"maxOrdersDay\":3,\"poiKeyword\":\"\",\"poiTypeCode\":\"\",\"scheme\":null,\"unit\":\"次\"},{\"appLevel\":5,\"catIcon\":\"https://tphoto.bxapp.cn/upload/assets/syjd.png\",\"catId\":\"bfd0af06fe612a5e7348b5718d1da7a2\",\"catName\":\"声音鉴定\",\"isOnline\":1,\"isTimelyAppointment\":1,\"levelOptions\":[],\"maxOrdersDay\":3,\"poiKeyword\":\"\",\"poiTypeCode\":\"\",\"scheme\":null,\"unit\":\"次\"}]},{\"catIcon\":\"https://tphoto.bxapp.cn/7b9f2e495562475f8367890dbf9bd579.png\",\"catName\":\"和平精英\",\"orderNo\":null,\"parentId\":\"471028758308978688\",\"subCatList\":[{\"appLevel\":5,\"catIcon\":\"\",\"catId\":\"c9c53944658043d5816df62f412f8db2\",\"catName\":\"zj_测试\",\"isOnline\":1,\"isTimelyAppointment\":1,\"levelOptions\":[],\"maxOrdersDay\":3,\"poiKeyword\":\"\",\"poiTypeCode\":\"\",\"scheme\":null,\"unit\":\"局\"}]},{\"catIcon\":\"https://tphoto.bxapp.cn/upload/assets/personal.png\",\"catName\":\"个人助理\",\"orderNo\":null,\"parentId\":\"326b3aaec3fde42ac5c0c202c3adf56c\",\"subCatList\":[{\"appLevel\":5,\"catIcon\":\"https://tphoto.bxapp.cn/90b12a258b1244f1ae9d9a59d367fbc0.png\",\"catId\":\"7a4466ce3869421caa3a782da212a2a0\",\"catName\":\"sh_test_1220\",\"isOnline\":1,\"isTimelyAppointment\":0,\"levelOptions\":[],\"maxOrdersDay\":3,\"poiKeyword\":\"\",\"poiTypeCode\":\"\",\"scheme\":null,\"unit\":\"min\"},{\"appLevel\":5,\"catIcon\":\"https://tphoto.bxapp.cn/b19a2a9e8c9b480cab68c2dda8a6879b.png\",\"catId\":\"a00f922b59934016bdeb57b995a07463\",\"catName\":\"嘿嘿嘿\",\"isOnline\":1,\"isTimelyAppointment\":1,\"levelOptions\":[],\"maxOrdersDay\":3,\"poiKeyword\":\"\",\"poiTypeCode\":\"\",\"scheme\":null,\"unit\":\"天\"}]},{\"catIcon\":\"https://tphoto.bxapp.cn/upload/assets/language.png\",\"catName\":\"外语\",\"orderNo\":null,\"parentId\":\"1adaf454908362a8e22fe5eb8cf8ad35\",\"subCatList\":[{\"appLevel\":5,\"catIcon\":\"https://tphoto.bxapp.cn/15368ae3fd954b0bba9ecb2b93a15ba4.png\",\"catId\":\"41ea6521dc7440e397b42a460febea3b\",\"catName\":\"zj\",\"isOnline\":1,\"isTimelyAppointment\":1,\"levelOptions\":[],\"maxOrdersDay\":3,\"poiKeyword\":\"\",\"poiTypeCode\":\"\",\"scheme\":null,\"unit\":\"天\"},{\"appLevel\":3,\"catIcon\":\"https://tphoto.bxapp.cn/upload/assets/Love_Consultant.png\",\"catId\":\"efbb1d9e39fade7899637664a2668fe2\",\"catName\":\"日语辅导\",\"isOnline\":1,\"isTimelyAppointment\":1,\"levelOptions\":[{\"key\":\"all\",\"value\":\"全部\"},{\"key\":\"second\",\"value\":\"N3\"},{\"key\":\"third\",\"value\":\"N4\"},{\"key\":\"four\",\"value\":\"N5\"}],\"maxOrdersDay\":3,\"poiKeyword\":\"\",\"poiTypeCode\":\"\",\"scheme\":null,\"unit\":\"小时\"},{\"appLevel\":5,\"catIcon\":\"\",\"catId\":\"b815854cce2c48f0975b9ec8af5aeda8\",\"catName\":\"asdasd\",\"isOnline\":1,\"isTimelyAppointment\":0,\"levelOptions\":[],\"maxOrdersDay\":3,\"poiKeyword\":\"\",\"poiTypeCode\":\"\",\"scheme\":null,\"unit\":\"1\"},{\"appLevel\":5,\"catIcon\":\"https://tphoto.bxapp.cn/upload/assets/english.png\",\"catId\":\"7cc133709fb2da581dc9cf1ed4baabfa\",\"catName\":\"英语陪练\",\"isOnline\":1,\"isTimelyAppointment\":1,\"levelOptions\":[{\"key\":\"all\",\"value\":\"全部\"},{\"key\":\"second\",\"value\":\"CET-4\"},{\"key\":\"third\",\"value\":\"CET-6\"},{\"key\":\"four\",\"value\":\"TEM4\"},{\"key\":\"five\",\"value\":\"TEM8\"}],\"maxOrdersDay\":3,\"poiKeyword\":\"\",\"poiTypeCode\":\"\",\"scheme\":null,\"unit\":\"小时\"}]}],\"success\":true,\"tid\":null}";

        JsonParser parser = new JsonParser();
        JsonObject obj = (JsonObject) parser.parse(json1);
        JsonParser parser1 = new JsonParser();
        JsonObject obj1 = (JsonObject) parser1.parse(json2);
        System.out.println(obj.equals(obj1));
    }
}
